version: 2.1
orbs:
  cypress: cypress-io/cypress@1.21.0
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          record: true
          parallel: true
          parallelism: 2
          group: 2 machines