version: 2.1
orbs:
  cypress: cypress-io/cypress@1.21.0
workflows:
  build:
    jobs:
      - cypress/run:
          install-command: npm install
          record: true
          parallel: true
          parallelism: 2
