version: 2.1
orbs:
  cypress: cypress-io/cypress@1.21.0
workflows:
  build:
    jobs:
      - cypress/run:
          install-command: npm install
          name: '3 machines'
          record: true
          parallel: true
          parallelism: 3
          group: '3x-electron on CircleCI'
          start: 'npm run start:ci'
