version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15

    working_directory: ~/knapsack-pro-cypress

    steps:
      # clone @knapsack-pro/core project
      - run:
          name: Checkout code of @knapsack-pro/core
          command: cd ~ && (git clone -b $CIRCLE_BRANCH --single-branch https://github.com/KnapsackPro/knapsack-pro-core-js.git || git clone --single-branch https://github.com/KnapsackPro/knapsack-pro-core-js.git)

      # set up @knapsack-pro/core project
      - restore_cache:
          name: Restoring Cache of @knapsack-pro/core
          keys:
            - v1-knapsack-pro-core-{{ checksum "~/knapsack-pro-core-js/package.json" }}
            # fallback to the latest cache if no exact match is found
            - v1-knapsack-pro-core-

      - run: cd ~/knapsack-pro-core-js && npm install
      - run: cd ~/knapsack-pro-core-js && npm run build
      - run: cd ~/knapsack-pro-core-js && sudo npm link

      - save_cache:
          name: Saving Cache of @knapsack-pro/core
          key: v1-knapsack-pro-core-{{ checksum "~/knapsack-pro-core-js/package.json" }}
          paths:
            - ~/knapsack-pro-core-js/node_modules

      # check out source code to working directory
      - checkout

      # restore, install and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run: npm link @knapsack-pro/core
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Run Cypress.io tests with @knapsack-pro/cypress using Knapsack Pro Queue Mode
          command: $(npm bin)/knapsack-pro-cypress  