version: 2.1
orbs:
  cypress: cypress-io/cypress@1.16.1
workflows:
  build:
    jobs:
      - cypress/install:
        build: 'npm install'

      - cypress/run:
        requires:
          - cypress/install
        recording: true
        parallel: true
        parallelism: 2