version: 2.1
orbs:
  cypress: cypress-io/cypress@1.21.0
workflows:
  build:
    jobs:
      - cypress/install:
          name: 'Cypress install'
          install-command: npm install

      - cypress/run:
          name: '2 machines'
          requires:
            - Cypress install
          record: true
          parallel: true
          parallelism: 2
