version: 2.1
orbs:
  cypress: cypress-io/cypress@1.21.0
workflows:
  build:
    jobs:
      - cypress/install:
          name: 'Cypress install'
          install-command: npm install
          post-steps:
            - run: npx cypress cache path
            - run: npx cypress cache list
            - run: npx cypress info

      - cypress/run:
          name: '3 machines'
          requires:
            - Cypress install
          record: true
          parallel: true
          parallelism: 3
          group: '3x-electron on CircleCI'
          start: 'npx cypress run'
